baseURL: "https://blog.mushan.top/"

# 主题
theme: LoveIt

# 网站标题
title: 木杉

defaultContentLanguage: zh
languageCode: zh
languageName: "简体中文"
# 是否包括中日韩文字
hasCJKLanguage: false

# 作者配置
author:
  name: 木杉
  email: "mushan.zb@gmail.com"
  link: "https://blog.mushan.top/"

# 默认每页列表显示的文章数目
paginate: 10

# 是否使用 robots.txt
enableRobotsTXT: true
# 是否使用 git 信息
# enableGitInfo: true
# 是否使用 emoji 代码
enableEmoji: true

# 版权描述，仅仅用于 SEO
# copyright: "2022 - 2023 木杉"

# 谷歌分析代号 [UA-XXXXXXXX-X]
# googleAnalytics: ""

# 忽略一些构建错误
ignoreErrors:
  - error-remote-getjson
  - error-missing-instag

# 用于 Hugo 输出文档的设置
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
