# 网站默认主题样式 ["auto", "light", "dark"]
defaultTheme: auto 

# 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ["sha256", "sha384", "sha512", "md5"]
fingerprint: "sha256"
# 日期格式
dateFormat: 2006-01-02

# 页面头部导航栏配置
header:
  # 桌面端导航栏模式 ["fixed", "normal", "auto"]
  desktopMode: fixed
  # 移动端导航栏模式 ["fixed", "normal", "auto"]
  mobileMode: auto
  # 页面头部导航栏标题配置
  title:
    # LOGO 的 URL
    logo: ""
    # 标题名称
    name: "木杉"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre: ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post: ""
    # 是否为标题显示打字机动画
    typeit: false

# 页面底部信息配置
footer:
  enable: true
  custom: ""
  # 是否显示 Hugo 和主题信息
  hugo: true
  # 是否显示版权信息
  copyright: true
  # 是否显示作者
  author: true
  # 网站创立年份
  since: 2020
  # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
  icp: "鲁ICP备18021776号"

# Section (所有文章) 页面配置
section:
  # section 页面每页显示文章数量
  paginate: 20
  # 日期格式 (月和日)
  dateFormat: 01-02
  # RSS 文章数目
  # rss: 10

# List (目录或标签) 页面配置
list:
  # list 页面每页显示文章数量
  paginate: 20
  # 日期格式 (月和日)
  dateFormat: 01-02
  # RSS 文章数目
  # rss: 10

# 搜索配置
search:
  enable: true
  # 搜索引擎的类型 ["lunr", "algolia"]
  type: lunr
  # 文章内容最长索引长度
  contentLength: 300
  # 搜索框的占位提示语
  placeholder: "请输入关键词"
  # 最大结果数目
  maxResultLength: 10
  # 结果内容片段长度
  snippetLength: 30
  # 搜索结果中高亮部分的 HTML 标签
  highlightTag: em
  # 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL: false
  # algolia:
  #   index: ""
  #   appID: ""
  #   searchKey: ""

# 主页配置
home:
  # RSS 文章数目
  rss: 10
  # 主页个人信息
  profile:
    enable: true
    # 主页显示的网站标题 (支持 HTML 格式)
    title: "木杉"
    # 主页显示的网站副标题 (允许 HTML 格式)
    subtitle: 木杉博客，记录生活
    # 是否为副标题显示打字机动画
    typeit: true
    # 是否显示社交账号
    social: true
    # 免责声明 (支持 HTML 格式)
    disclaimer: ""
  posts:
    enable: true
    # 主页每页显示文章数量
    paginate: 5

# 作者的社交信息设置
social:
  GitHub: "https://github.com/mushan-zb"
  Email: "mushan.zb@gmail.com"
  RSS: true

# 文章页面全局配置
page:
  # 是否在主页隐藏文章
  hiddenFromHomePage: false
  # 是否在搜索结果中隐藏文章
  hiddenFromSearch: false
  # 是否使用 twemoji
  twemoji: false
  # 是否使用 lightgallery
  lightgallery: false
  # 是否使用 ruby 扩展语法
  ruby: false
  # 是否使用 fraction 扩展语法
  fraction: false
  # 是否使用 fontawesome 扩展语法
  fontawesome: false
  # 是否在文章页面显示原始 Markdown 文档链接
  linkToMarkdown: true
  # 是否在 RSS 中显示全文内容
  rssFullText: false
  # 目录配置
  toc:
    # 是否使用目录
    enable: true
    # 是否使侧边目录自动折叠展开
    auto: true
  # 代码配置
  code:
    # 是否显示代码块的复制按钮
    copy: true
    # 默认展开显示的代码行数
    maxShownLines: 30
  # 文章页面的分享信息设置
  share:
    enable: false
  # 评论系统设置
  comment:
    enable: true
    # Gitalk 评论系统设置
    gitalk:
      enable: true
      owner: "mushan-zb"
      repo: "mushan-zb.github.io"
      clientId: "530a27e2e7c66133b4ea"
      clientSecret: "f8d3909650ee2a364ca9a0067be5252483ca5563"
    # Valine 评论系统设置
    # valine:
    #   enable: false
    #   appId: ""
    #   appKey: ""
    #   placeholder: ""
    #   avatar: mp
    #   meta: ""
    #   pageSize: 10
    #   # 为空时自动适配当前主题 i18n 配置
    #   lang: ""
    #   visitor: true
    #   recordIP: true
    #   highlight: true
    #   enableQQ: false
    #   serverURLs: ""
    #   # emoji 数据文件名称, 默认是 "google.yml"
    #   # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
    #   # 位于 "themes/LoveIt/assets/lib/valine/emoji/" 目录
    #   # 可以在你的项目下相同路径存放你自己的数据文件:
    #   # "assets/lib/valine/emoji/"
    #   emoji: ""
  # 页面 SEO 配置
  # seo:
  #   # 图片 URL
  #   images: []
  #   # 出版者信息
  #   publisher:
  #     name: ""
  #     logoUrl: ""

#  TypeIt 配置
typeit:
  # 每一步的打字速度 (单位是毫秒)
  speed: 300
  # 光标的闪烁速度 (单位是毫秒)
  cursorSpeed: 800
  # 光标的字符 (支持 HTML 格式)
  cursorChar: "|"
  # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
  duration: 5000

# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
# verification:
#   google: ""
#   bing: ""
#   yandex: ""
#   pinterest: ""
#   baidu: ""

# 网站 SEO 配置
# seo:
#   # 图片 URL
#   image: ""
#   # 缩略图 URL
#   thumbnailUrl: ""

# 网站分析配置
# analytics:
#   enable: false
#   # Google Analytics
#   google:
#     id: ""
#     # 是否匿名化用户 IP
#     anonymizeIP: true
#   # Fathom Analytics
#   fathom:
#     id: ""
#     # 自行托管追踪器时的主机路径
#     server: ""
#   # Plausible Analytics
#   plausible:
#     dataDomain: ""
#   # Yandex Metrica
#   yandexMetrica:
#     id: ""
