baseURL: "https://blog.mushan.top/"
languageCode: "zh"
title: '木杉'
paginate: 5 # 每页展示数目
theme: PaperMod
publishDir: docs # 默认叫 publish，但 github pages 只能只能识别 / /docs 建议使用 docs

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  # 网页 header 中的 meta 信息
  title: 木杉博客
  description: "记录生活、学习的点点滴滴"
  keywords: [木杉, mushan, 博客, Blog, github pages, PaperMod]

  author: 木杉
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: 木杉小站
    subtitle: "欢迎来到木杉的博客！！！"
    # imageUrl: ""
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    buttons:
      - name: 文章
        url: posts
      - name: 分类
        url: categories

  socialIcons:
    - name: github
      url: "https://github.com/mushan-zb"
    - name: QQ
      url: "img/qq.png"
    - name: WeChat
      url: "img/wechat.png"
    - name: tiktok
      url: "img/tiktok.png"
    - name: email
      url: "mailto:mushan.zb@gmail.com"
  
menu:
  main:
    - identifier: search
      name: 🔍搜索
      url: search
      weight: 1
    - identifier: archives
      name: ⏱时间轴
      url: archives/
      weight: 2
    - identifier: posts
      name: 📚文章
      url: posts
      weight: 3
    - identifier: categories
      name: 🧩分类
      url: categories
      weight: 4
    - identifier: tags
      name: 🔖标签
      url: tags
      weight: 5
    # - identifier: about
    #   name: 🙋🏻‍♂️关于
    #   url: about
    #   weight: 50
    # - identifier: links
    #   name: 🤝友链
    #   url: links
    # - identifier: home
    #   name: 🏠主页
    #   url: /
    #   weight: 2
    # - identifier: tech
    #   name: 👨🏻‍💻技术文章
    #   url: posts/tech
    #   weight: 5
    # - identifier: life
    #   name: 🏖记录生活
    #   url: posts/life
    #   weight: 6