main:
  - identifier: "posts"
    weight: 1
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre: ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post: ""
    name: "文章"
    url: "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title: ""
  - identifier: "tags"
    weight: 2
    pre: ""
    post: ""
    name: "标签"
    url: "/tags/"
    title: ""
  - identifier: "categories"
    weight: 3
    pre: ""
    post: ""
    name: "分类"
    url: "/categories/"
    title: ""